core/urls.py
from core.hod_views import *
from core.staff_views import *
from core.views import *
from core.student_views import *
from django.urls import path

urlpatterns = [
    path("home/", home, name="home"),
    path("", signin, name="login"),
    path("dologin/", doLogin, name="doLogin"),
    path("dologout/", doLogout, name="logout"),

    # Profile Update
    path("profile/", profile, name="profile"),
    path("profile_update", profile_update, name="profile_update"),

    # HoD Panel URL

    path("hod/home/", hod_home, name="hod_home"),
    # HOD Students URLS
    path("add/students/", add_students, name="add_students"),
    path("hod/student/view/", hod_student_view, name="hod_student_view"),
    path("hod/student/edit/<str:id>", edit_student, name="edit_student"),
    path('hod/delete_student/<str:id>/', delete_student, name='delete_student'),
    # HOD Course URLS
    path('hod/add_course/', add_course, name='add_course'),
    path('hod/view_course/', view_course, name='view_course'),
    path('edit_course/<int:id>/', edit_course, name='edit_course'),
    path('delete_course/<int:id>/', delete_course, name='delete_course'),
    # HOD STAFF URLS
    path('hod/add_staff/', add_staff, name='add_staff'),
    path('hod/view_staff/', view_staff, name='view_staff'),
    path('edit_staff/<int:id>/', edit_staff, name='edit_staff'),
    path('delete_staff/<int:id>/', delete_course, name='delete_staff'),
    path("hod/staff_leave/", staff_leave_view, name="staff_leave_view"),
    path("hod/staff_leave/approve/<str:id>", staff_leave_approve, name="staff_leave_approve"),
    path("hod/staff_leave/approve/<str:id>", staff_leave_disapprove, name="staff_leave_disapprove"),
    path("hod_staffeed_back/", staff_feedback_reply, name="hod_staff_feedback_reply"),
    path("hod_staffeed_back/save", staff_feedback_reply_save, name="hod_staff_feedback_reply_save"),
    path("hod_student_feed_back/", student_feedback_reply, name="student_feedback_reply"),
    path("hod_student_feed_back/save/", student_feedback_reply_save, name="student_feedback_reply_save"),
    path("hod/student_leave/", student_leave_view, name="student_leave_view"),
    path("hod/student_leave/approve/<int:id>/", student_leave_approve, name="student_leave_approve"),
    path("hod/student_leave/disapprove/<int:id>/", student_leave_disapprove, name="student_leave_disapprove"),
    # Subjects
    path("hod/add/subject/", add_subject, name="add_subject"),
    path('hod/view_subject/', view_subject, name='view_subject'),
    path('edit_subject/<int:id>/', edit_subject, name='edit_subject'),
    path('delete_subject/<int:id>/', delete_subject, name='delete_subject'),

    # Session URLS
    path('hod/add/', add_session_year, name='add_session_year'),
    path('hod/view/', view_session_year, name='view_session_year'),
    path('hod/update/<int:id>/', update_session_year, name='update_session_year'),
    path('hod/delete/<int:id>/', delete_session_year, name='delete_session_year'),

    # This is Staff Urls

    path("staff/home/", staff_home, name="staff_home"),
    path("hod/staff_notification", staff_send_notification, name="staff_send_notification"),
    path("hod/staff/save_notification", save_staff_notification, name="save_staff_notification"),
    path("hod/staff/notification", staff_view_notification, name="staff_view_notification"),
    path("staff/mark_done/notification<str:status>", mark_done, name="mark_done"),
    path("staff/apply_leave/", staff_apply_leave, name="staff_apply_leave"),
    path("staff/apply_leave/save", staff_leave_save, name="staff_leave_save"),
    path("staff/feedback/", staff_feedback, name="staff_feedback"),
    path("staff/feedback/save/", staff_feedback_save, name="staff_feedback_save"),
    path("staff/take/attendance/", staff_take_attendance, name="staff_take_attendance"),
    path("staff/save/attendance/", staff_save_attendance, name="staff_save_attendance"),
    path("staff/view/attendance/", staff_view_attendance, name="staff_view_attendance"),

    # StudentURL

    path("student/home", student_home, name="student_home"),
    path('send-notification/', student_send_notification, name='student_send_notification'),
    path('send-notification/save', student_send_notification_save, name='student_send_notification_save'),
    path("student/notification/", student_notification, name="student_notification"),
    path('notifications/mark-done/<int:notification_id>/', mark_done, name='mark_done'),
    path("student/feedback",student_feedback,name="student_feedback"),
    path("student/feedback/save", student_feedback_save, name="student_feedback_save"),
    path("student/apply_leave/", student_apply_leave, name="student_apply_leave"),
    path("student/apply_leave/save/", student_leave_save, name="student_leave_save"),
]

student_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class CustomUser(AbstractUser):
    HOD = 1
    STAFF = 2
    STUDENT = 3
    USER_TYPE_CHOICES = [
        (HOD, 'HOD'),
        (STAFF, 'Staff'),
        (STUDENT, 'Student'),
    ]

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=HOD)
    profile_pic = models.ImageField(upload_to='profile_pic')

    def __str__(self):
        return self.username


class Course(models.Model):
    name = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class SessionYear(models.Model):
    session_start = models.CharField(max_length=100)
    session_end = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.session_start} - {self.session_end} "


class Staff(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField()
    gender = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.admin.first_name} - {self.admin.last_name} "


class Subject(models.Model):
    name = models.CharField(max_length=150)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class StaffNotification(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    status = models.IntegerField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.staff_id.admin.first_name


class StaffLeave(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=100)
    message = models.TextField()
    status = models.IntegerField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.staff_id.admin.first_name


class StaffFeedBack(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feed_back = models.TextField()
    feed_back_reply = models.TextField()
    status = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.staff_id.admin.first_name


class Student(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField()
    gender = models.CharField(max_length=100)
    course_id = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
    session_year_id = models.ForeignKey(SessionYear, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


class StudentNotification(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    status = models.IntegerField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student_id.admin.first_name


class StudentFeedBack(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    feed_back = models.TextField()
    feed_back_reply = models.TextField()
    status = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student_id.admin.first_name


class StudentLeave(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.CharField(max_length=100)  # Consider using DateField
    message = models.TextField()
    status = models.IntegerField(null=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student.admin.first_name


class Attendance(models.Model):
    subject_id = models.ForeignKey(Subject,on_delete=models.DO_NOTHING)
    attendance_date = models.DateField()
    session_year_id = models.ForeignKey(SessionYear,on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject_id.name


class AttendanceReport(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.DO_NOTHING)
    attendance_id = models.ForeignKey(Attendance,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.student_id.admin.first_name

templates/includes/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="card-body">
        <div id="student_gender"></div>
    </div>

    <script>
        'use strict';

        $(document).ready(function() {


        var options = {
          series: [{{student_count}},{{staff_count}},{{subject_count}},{{curse_count}}],
          chart: {
          height: 350,
          width: '100%',
          type: 'pie',
        },
        labels: ['Student', 'Staff', 'Subject', 'Course', ],
        responsive: [{
          breakpoint: 480,
          options: {
            chart: {
              width: 200
            },
            legend: {
              position: 'bottom'
            }
          }
        }]
        };

        var chart = new ApexCharts(document.querySelector("#all_details"), options);
        chart.render();

            // Bar chart
            if ($('#student_gender').length > 0) {
                var optionsBar = {
                    chart: {
                        type: 'bar',
                        height: 350,
                        width: '100%',
                        stacked: true,
                        toolbar: {
                            show: false
                        },
                    },
                    dataLabels: {
                        enabled: false
                    },
                    plotOptions: {
                        bar: {
                            columnWidth: '45%',
                        }
                    },
                    series: [{
                        name: "Boys",
                        color: '#fdbb38',
                        data: [{{ student_gender_male }}],
                    }, {
                        name: "Girls",
                        color: '#19affb',
                        data: [{{ student_gender_female }}],
                    }],
                    labels: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
                    xaxis: {
                        labels: {
                            show: false
                        },
                        axisBorder: {
                            show: false
                        },
                        axisTicks: {
                            show: false
                        },
                    },
                    yaxis: {
                        axisBorder: {
                            show: false
                        },
                        axisTicks: {
                            show: false
                        },
                        labels: {
                            style: {
                                colors: '#777'
                            }
                        }
                    },
                    title: {
                        text: '',
                        align: 'left',
                        style: {
                            fontSize: '18px'
                        }
                    }
                }

                var chartBar = new ApexCharts(document.querySelector('#student_gender'), optionsBar);
                chartBar.render();
            }
        });
    </script>
</body>
</html>

templates/includes/footer.html
{% load static %}
            <footer>
               <p>Copyright © 2020 AQTECH.</p>
            </footer>

templates/includes/header.html
{% load static %}
<div class="header">
    <div class="header-left">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'assets/img/logo.png' %}" alt="Logo">
        </a>
        <a href="{% url 'home' %}" class="logo logo-small">
            <img src="{% static 'assets/img/logo-small.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>
    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fas fa-align-left"></i>
    </a>
    <div class="top-nav-search mt-3">
        <h4><strong>Welcome</strong> <span>{{ user.first_name }} {{ user.last_name }}</span></h4>
    </div>
    <a class="mobile_btn" id="mobile_btn">
        <i class="fas fa-bars"></i>
    </a>
    <ul class="nav user-menu">
        <li class="nav-item dropdown noti-dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <i class="far fa-bell"></i> <span class="badge badge-pill">3</span>
            </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{{ user.profile_pic.url }}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
                                        <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-11.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">International Software Inc</span> has sent you an invoice in the amount of <span class="noti-title">$218</span></p>
                                        <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-17.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request for <span class="noti-title">Apple iPhone XR</span></p>
                                        <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="#">
                                <div class="media">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-13.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Mercury Software Inc</span> added a new product <span class="noti-title">Apple MacBook Pro</span></p>
                                        <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="#">View all Notifications</a>
                </div>
            </div>
        </li>
        <li class="nav-item dropdown has-arrow">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                {% if user.profile_pic  == "" %}
                 <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-13.jpg' %}">
                                    </span>
                {% else %}
                <span class="user-img"><img class="rounded-circle" src="{{ user.profile_pic.url }}" width="31" alt="User Image"></span>
            {% endif %}
            </a>
            <div class="dropdown-menu">
                <div class="user-header">
                    <div class="avatar avatar-sm">
                        <img src="{{ user.profile_pic.url }}" alt="User Image" class="avatar-img rounded-circle">
                    </div>
                    <div class="user-text">
                        <h6>{{ user.first_name }} {{ user.last_name }}</h6>
                       <p class="text-muted mb-0">{{ user.get_user_type_display }}</p>


                    </div>
                </div>
                <a class="dropdown-item" href="{% url 'profile' %}">My Profile</a>
                <a class="dropdown-item" href="inbox.html">Inbox</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</div>

templates/includes/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert" aria-label="{{ message }}">
      <strong>{{ message.tags|title }}</strong>
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}

templates/includes/sidebar.html
{% load static %}


<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            {% if user.user_type == 1 %}
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-tachometer-alt"></i><span> Dashboard</span> </a>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-user-graduate"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'add_students' %}">Student Add</a></li>
                        <li><a href="{% url 'hod_student_view' %}">Student View</a></li>
                    </ul>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Staff</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'view_staff' %}">Staff View</a></li>
                        <li><a href="{% url 'add_staff' %}">Staff Add</a></li>
                    </ul>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-book-open"></i><span> Course</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'add_course' %}">Course Add</a></li>
                        <li><a href="{% url 'view_course' %}">Course View</a></li>
                    </ul>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'view_subject' %}">Subject View</a></li>
                        <li><a href="{% url 'add_subject' %}">Subject Add</a></li>
                    </ul>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-clock"></i> <span> Session</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'view_session_year' %}">Session View</a></li>
                        <li><a href="{% url 'add_session_year' %}">Session Add</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fas fa-clipboard-list"></i> <span> Attendance</span> </a>
                </li>
                <li>
                    <a href="{% url 'staff_send_notification' %}"><i class="fas fa-bell"></i><span> Send Staff Notification</span> </a>
                </li>
                <li>
                    <a href="{% url 'student_send_notification' %}"><i class="fas fa-bell"></i><span> Send Student Notification</span> </a>
                </li>
                <li>
                    <a href="{% url 'hod_staff_feedback_reply' %}"><i class="fas fa-comments"></i><span> Staff Feedback</span> </a>
                </li>
                <li>
                    <a href="{% url 'student_feedback_reply' %}"><i class="fas fa-comments"></i> <span> Student Feedback</span> </a>
                </li>
                <li>
                    <a href="{% url 'staff_leave_view' %}"><i class="fas fa-scroll"></i> <span> Staff Leave</span> </a>
                </li>
                <li>
                    <a href="{% url 'student_leave_view' %}"><i class="fas fa-scroll"></i> <span> Student Leave</span> </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i><span> Logout</span> </a>
                </li>
            </ul>
            {% elif user.user_type == 2 %}
            <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-tachometer-alt"></i><span> Dashboard</span> </a>
                </li>
                 <li>
                    <a href="{% url 'staff_take_attendance' %}"><i class="fas fa-calendar-alt"></i><span> Take Attendence</span> </a>
                </li>
                 <li>
                    <a href="{% url 'staff_view_attendance' %}"><i class="fas fa-calendar-alt"></i><span> View/Update Attendence</span> </a>
                </li>
                 <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-poll-h"></i><span> Add Result</span> </a>
                </li>
                 <li>
                    <a href="{% url 'staff_apply_leave' %}"><i class="fas fa-envelope-open"></i><span> Apply For Leave</span> </a>
                </li>
                 <li>
                    <a href="{% url 'staff_feedback' %}"><i class="fas fa-comment"></i><span> Send FeedBack</span> </a>
                </li>
                <li>
                    <a href="{% url 'staff_view_notification' %}"><i class="fas fa-bell"></i><span> Notification</span> </a>
                </li>
                 <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-sign-out-alt"></i><span> Logout</span> </a>
                </li>


            </ul>
            {% else %}
             <ul>
                <li class="menu-title">
                    <span>Main Menu</span>
                </li>
                <li>
                    <a href="{% url 'student_home' %}"><i class="fas fa-tachometer-alt"></i><span> Dashboard</span> </a>
                </li>
                  <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-calendar-alt"></i><span> View Attendance</span> </a>
                </li>
                  <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-poll"></i><span> View Result</span> </a>
                </li>
                  <li>
                    <a href="{% url 'student_apply_leave' %}"><i class="fas fa-pray"></i><span> Apply for Leave</span> </a>
                </li>
                  <li>
                    <a href="{% url 'student_feedback' %}"><i class="fas fa-comment"></i><span> Send Feedback</span> </a>
                </li>
                  <li>
                    <a href="{% url 'student_notification' %}"><i class="fas fa-bell"></i><span> Send Notification</span> </a>
                </li>
                   <li>
                    <a href="{% url 'hod_home' %}"><i class="fas fa-sign-out-alt"></i><span> Logout</span> </a>
                </li>
             </ul>
            {% endif %}
        </div>
    </div>
</div>